### ISSUE TITLE
consolidate similar functions for image and tabular data

### ISSUE THREAD

**Issue by zzsi** [kungfuai/kaishi#22]
- Loading. https://github.com/kungfuai/kaishi/blob/master/kaishi/tabular.py#L63, https://github.com/kungfuai/kaishi/blob/master/kaishi/util/file.py#L76
- Dedup. https://github.com/kungfuai/kaishi/blob/master/kaishi/util/filters.py#L5, and https://github.com/kungfuai/kaishi/blob/master/kaishi/tabular.py#L122

Perhaps do this by inheritance from an abstract class that covers both image and tabular data.

**Comment by mwharton3** [comment]
These are both completed (each inherits from the `FileGroup` class)
